#!/usr/bin/env python3
"""Generate registry documentation from the live FairLMs registries.

The point of this script is the claim it lets you make in the paper: the
registry tables in the docs are generated from the registries themselves and
cannot drift from the code. Run it in CI with --check so a stale table fails
the build.

    python scripts/gen_registry_docs.py            # write
    python scripts/gen_registry_docs.py --check    # fail if out of date

Every attribute read below is one that actually exists on the objects:
``FairnessMetric`` declares ``name``, ``bias_type`` and ``architectures``;
``DatasetDiagnostic`` declares ``name`` and annotates its ``compute`` evidence
parameter; loaders are ``FairnessDataset`` subclasses exported from
``fairLMs.datasets``.
"""

from __future__ import annotations

import argparse
import inspect
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# Generate from this source tree even when another fairLMs version is installed.
sys.path.insert(0, str(ROOT.parent))
DOCS = ROOT / "docs" / "registry"

HEADER = "<!-- GENERATED BY scripts/gen_registry_docs.py: DO NOT EDIT BY HAND -->\n\n"


def _fmt(seq) -> str:
    if not seq:
        return "n/a"
    if isinstance(seq, str):
        return f"`{seq}`"
    return ", ".join(f"`{s}`" for s in seq)


def _summary(obj) -> str:
    """First sentence of a docstring, on one line."""
    doc = inspect.getdoc(obj) or ""
    first = doc.strip().split("\n\n")[0].replace("\n", " ").strip()
    return first or "n/a"


def _aliases() -> dict:
    """Map class -> short alias exported alongside it (CPS, AUL, DisCo, ...)."""
    import fairLMs.metrics as M

    out = {}
    for name in M.__all__:
        obj = getattr(M, name, None)
        if not inspect.isclass(obj):
            continue
        # An alias is a second public name bound to a class whose own __name__
        # differs from the exported name.
        if obj.__name__ != name:
            out.setdefault(obj, []).append(name)
    return out


def metrics_page() -> str:
    from fairLMs.metrics import METRIC_REGISTRY

    aliases = _aliases()
    rows = []
    for name, cls in sorted(METRIC_REGISTRY.items()):
        rows.append(
            "| `{name}` | `{cls}` | {alias} | {bias} | {arch} | {task} |".format(
                name=name,
                cls=cls.__name__,
                alias=_fmt(sorted(aliases.get(cls, ()))),
                bias=f"`{cls.bias_type}`" if cls.bias_type else "n/a",
                arch=_fmt(cls.architectures),
                task=_fmt(cls.required_task),
            )
        )
    n_free = sum(1 for c in METRIC_REGISTRY.values() if c.required_task is None)

    return (
        HEADER
        + "# Metrics\n\n"
        + f"{len(rows)} registered metrics. Instantiate any of them by registry "
        "name with `fairLMs.metrics.get_metric(name)`, or import the class "
        "directly. Every metric exposes "
        "`compute(model, data) -> MetricResult`.\n\n"
        "`bias_type` and `architectures` document where a metric sits in the "
        "taxonomy. **`required_task` is enforced**: it names the head the "
        "checkpoint must be loaded with, and a mismatch is refused before the "
        "metric runs rather than surfacing as a missing attribute or as "
        "numbers read off an untrained head. See "
        "[Models](../api/models.md).\n\n"
        f"The {n_free} metrics with no required task score precomputed "
        "predictions, call an API, or take a plain callable, so they impose no "
        "requirement on how a model was loaded.\n\n"
        "| Registry name | Class | Alias | Bias type | Architectures | Required task |\n"
        "|---|---|---|---|---|---|\n" + "\n".join(rows) + "\n"
    )


def loaders_page() -> str:
    """Loaders are FairnessDataset subclasses exported from fairLMs.datasets.

    There is no separate loader registry; the public export list *is* the
    registry, so this table is derived from it.
    """
    import fairLMs.datasets as DS
    from fairLMs.datasets import FairnessDataset

    classes = []
    for name in sorted(DS.__all__):
        cls = getattr(DS, name)
        if (
            inspect.isclass(cls)
            and issubclass(cls, FairnessDataset)
            and cls is not FairnessDataset
            # An alias is a second export bound to a class already listed under
            # its own __name__ (EEC -> EquityEvaluationCorpus).
            and cls.__name__ == name
        ):
            classes.append((name, cls))

    alias_names = {
        cls: sorted(
            n for n in DS.__all__ if getattr(DS, n, None) is cls and n != cls.__name__
        )
        for _, cls in classes
    }

    rows = []
    origins = {}
    for name, cls in classes:
        params = [
            p for p in inspect.signature(cls.__init__).parameters if p not in ("self",)
        ]
        origins.setdefault(cls.data_origin, []).append(name)
        rows.append(
            "| `{name}` | {alias} | {summary} | {origin} | {params} |".format(
                name=name,
                alias=_fmt(alias_names[cls]),
                summary=_summary(cls),
                origin=cls.data_origin,
                params=_fmt(params),
            )
        )

    breakdown = "\n".join(
        f"- **{origin}**: {_fmt(sorted(names))}"
        for origin, names in sorted(origins.items())
    )

    return (
        HEADER
        + "# Loaders\n\n"
        + f"{len(rows)} dataset loaders behind one interface: each subclasses "
        "`FairnessDataset` and exposes `load()`, returning examples that a "
        "metric's `data` argument accepts directly.\n\n"
        "Each benchmark retains its own license, and where it comes from "
        "differs. Some are redistributed with the package, some are pulled "
        "from the Hugging Face Hub the first time you load them, and some are "
        "only distributed from their own project page, so their loader needs a "
        "`root=` pointing at your copy and will not download anything:\n\n"
        + breakdown
        + "\n\n"
        "| Loader | Alias | Description | Data origin | Constructor arguments |\n"
        "|---|---|---|---|---|\n" + "\n".join(rows) + "\n"
    )


def diagnostics_page() -> str:
    from fairLMs.diagnostics import DIAGNOSTIC_REGISTRY

    rows = []
    for name, cls in sorted(DIAGNOSTIC_REGISTRY.items()):
        evidence = inspect.signature(cls.compute).parameters.get("evidence")
        ann = getattr(evidence, "annotation", None)
        ann = ann if isinstance(ann, str) else getattr(ann, "__name__", "n/a")
        # A union annotation contains a pipe, which would end the table cell.
        ann = ann.replace("|", "\\|")
        rows.append(
            "| `{name}` | `{cls}` | `{ev}` | {summary} |".format(
                name=name, cls=cls.__name__, ev=ann, summary=_summary(cls)
            )
        )

    from fairLMs.diagnostics import (
        BACKEND_CONSTRUCTION_SLOTS,
        CONSTRUCTION_BACKEND_REQUIREMENTS,
        CONSTRUCTION_SLOTS,
    )

    reference_backends = {
        "b_equiv": "HuggingFaceEmbeddingBackend",
        "b_gram": "LanguageToolGrammarBackend",
        "b_diff_dep": "SpacyDependencyBackend",
    }
    backend_rows = [
        "| `{slot}` | `{cls}` | `{protocol}` | `{reference}` | `{view}` | `{code}` |".format(
            slot=slot,
            cls=DIAGNOSTIC_REGISTRY[slot].__name__,
            protocol=CONSTRUCTION_BACKEND_REQUIREMENTS[slot]["required_protocol"],
            reference=reference_backends[slot],
            view=CONSTRUCTION_BACKEND_REQUIREMENTS[slot]["required_view"],
            code=CONSTRUCTION_BACKEND_REQUIREMENTS[slot]["reason_code"],
        )
        for slot in CONSTRUCTION_SLOTS
        if slot in BACKEND_CONSTRUCTION_SLOTS
    ]

    return (
        HEADER
        + "# Diagnostics\n\n"
        + f"{len(rows)} registered components. Each reports one of `ready`, "
        "`blocked`, `not_applicable`, `failed`. Unavailable evidence is never "
        "reported as a measured zero.\n\n"
        "Diagnostics consume explicit evidence objects and a "
        "`DatasetAuditSpec`, never a model. Run one component through "
        "`audit_representativeness`, `audit_leakage` or `audit_scores`, the "
        "construction vector through `audit_construction`, and several "
        "evidence views at once through `audit_dataset`.\n\n"
        "Every registered diagnostic constructs with zero arguments, which is "
        "what `get_diagnostic(name)` needs. Several of them then report "
        "`blocked` for their own missing configuration -- `b_min` without an "
        "identity mask, `b_opt` without an option-role contrast, `b_frame` "
        "without a frame predicate, `b_leak` on raw text without an "
        "extraction configuration, and `b_equiv`, `b_gram`, `b_diff_dep` "
        "without a `backend`. That is the designed answer, not a defect: each "
        "of those settings is part of the estimand and is never inferred.\n\n"
        "| Component | Class | Evidence | Description |\n|---|---|---|---|\n"
        + "\n".join(rows)
        + "\n\n"
        + "## Construction slots\n\n"
        + "`b_constr` is published as a vector of "
        f"{len(CONSTRUCTION_SLOTS)} independent components in the fixed order "
        + ", ".join(f"`{slot}`" for slot in CONSTRUCTION_SLOTS)
        + ", never as an aggregate score. `construction_vector(report)` "
        "returns them in that order, since a report alphabetizes its "
        "components.\n\n"
        + f"The {len(backend_rows)} slots below read a quantity that needs an "
        "optional backend: a sentence embedding, a grammatical-error count or a "
        "dependency-tree depth. Each is a registered class that takes `backend=`; "
        "reference implementations live in `fairLMs.diagnostics.backends`. The "
        "embedding backend runs on the core dependencies, while the grammar and "
        "parser backends need the `grammar` and `parse` extras "
        "(`pip install \"fairLMs[nlp]\"` installs both). Without a backend the slot "
        "is `blocked` with the reason code below, but only after the precedence "
        "every component shares: when it was not requested, the target kind is "
        "unsupported or its required evidence view is absent for the audited "
        "axis, it is `not_applicable` for that ordinary reason "
        "(`component_not_requested`, `target_kind_not_supported`, "
        "`evidence_view_not_supplied`), or whatever a caller override declares. "
        "Status alone therefore does not identify a backend slot -- "
        "`BACKEND_CONSTRUCTION_SLOTS` and `CONSTRUCTION_BACKEND_REQUIREMENTS` "
        "do. A missing backend blocks only its own slot and never the rest of "
        "the vector.\n\n"
        "| Slot | Class | Protocol | Reference backend | Required view | "
        "Reason code without a backend |\n"
        "|---|---|---|---|---|---|\n" + "\n".join(backend_rows) + "\n"
    )


#: Ordered as the book chapter presents the intervention categories.
_CATEGORY_BLURB = {
    "pre": "Applied to the data before training. Transform evidence, not models.",
    "in": "Loss components composable with a normal training loop. These return "
    "a callable objective, never a trained model: there is no trainer in the "
    "core package.",
    "intra": "Edits to a loaded model. Each returns a `ModelAdapter`, so any "
    "metric re-evaluates the mitigated model without modification.",
    "post": "Decision rules fitted on outputs. Serializable, and applied "
    "without the model that produced the scores.",
}


def mitigation_page() -> str:
    from fairLMs.mitigation import MITIGATOR_REGISTRY

    sections = []
    for category, blurb in _CATEGORY_BLURB.items():
        rows = []
        for name, cls in sorted(MITIGATOR_REGISTRY.items()):
            if cls.category != category:
                continue
            rows.append(
                "| `{name}` | `{cls}` | {access} | {arch} | {req} | {acc} |".format(
                    name=name,
                    cls=cls.__name__,
                    access=f"`{cls.access}`",
                    arch=_fmt(sorted(cls.architectures)),
                    req=_fmt(sorted(cls.requires)) if cls.requires else "-",
                    acc=_fmt(sorted(t.__name__ for t in cls.accepts)),
                )
            )
        sections.append(
            f"## {category.capitalize()}-processing\n\n{blurb}\n\n"
            "| Component | Class | Access | Architectures | Requires | Accepts |\n"
            "|---|---|---|---|---|---|\n" + "\n".join(rows) + "\n"
        )

    return (
        HEADER
        + "# Mitigators\n\n"
        + f"{len(MITIGATOR_REGISTRY)} registered components. Each declares an "
        "intervention category, an access level, supported architectures, the "
        "capabilities it needs from a model, and the evidence containers it "
        "consumes. Applicability is decided from those declarations by the same "
        "matcher the metrics use, and an unsatisfiable pairing is refused by "
        "name.\n\n"
        "Access levels are ordered `black_box` < `gray_box` < `white_box`; a "
        "component declares the **minimum** it needs.\n\n"
        + "\n".join(sections)
        + "\n## Not provided\n\n"
        "Named in the paper as extension points and deliberately absent from "
        "this registry: RLHF, DPO, Constitutional AI and other "
        "preference-optimized training loops; UniDetox; the "
        "influence-estimation half of IF-Guide; GeDi, RAD, DExperts, FairSteer, "
        "ARGRE and other guided-decoding methods; LSDM; FairMed; "
        "gender-constrained beam search; model-based rewriting.\n\n"
        "Named in the book chapter but not provided here, recorded so that a "
        "reader comparing the two does not mistake omission for oversight: "
        "conceptor debiasing; pruning and ablation; the no-attribute "
        "(name-proxy) setting; Co2PT; BiasUnlearn; data filtering and toxicity "
        "removal; dataset curation and balanced collection; output filtering "
        "and safety classification; refusal policies and content moderation; "
        "counterfactual data *substitution*. The book's bias diagnosis and data "
        "auditing family is covered, but by the "
        "[diagnostics](diagnostics.md) layer.\n"
    )


PAGES = {
    "metrics.md": metrics_page,
    "loaders.md": loaders_page,
    "diagnostics.md": diagnostics_page,
    "mitigation.md": mitigation_page,
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if pages are stale")
    args = ap.parse_args()

    DOCS.mkdir(parents=True, exist_ok=True)
    stale = []

    for filename, builder in PAGES.items():
        path = DOCS / filename
        new = builder()
        if args.check:
            old = path.read_text() if path.exists() else ""
            if old != new:
                stale.append(filename)
        else:
            path.write_text(new)
            print(f"wrote {path}")

    if stale:
        print("STALE (run scripts/gen_registry_docs.py): " + ", ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
